admin_ekyna_product:
    resource: 'routing/admin.yaml'
    prefix:   '%ekyna_admin.routing_prefix%/catalog'

ekyna_product:
    resource: 'routing/front.yaml'

ekyna_product_loader:
    resource: .
    type: product_routing
