ekyna_product_attribute_group_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.attribute_group.controller:homeAction" }
    methods: [GET]

ekyna_product_attribute_group_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.attribute_group.controller:listAction" }
    methods: [GET|POST]

ekyna_product_attribute_group_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.attribute_group.controller:newAction" }
    methods: [GET|POST]

ekyna_product_attribute_group_admin_show:
    path: /{attributeGroupId}/show
    defaults: { _controller: "ekyna_product.attribute_group.controller:showAction" }
    methods: [GET]
    requirements:
        attributeGroupId: \d+

ekyna_product_attribute_group_admin_edit:
    path: /{attributeGroupId}/edit
    defaults: { _controller: "ekyna_product.attribute_group.controller:editAction" }
    methods: [GET|POST]
    requirements:
        attributeGroupId: \d+

ekyna_product_attribute_group_admin_move_up:
    path: /{attributeGroupId}/moveup
    defaults: { _controller: "ekyna_product.attribute_group.controller:moveUpAction" }
    methods: [GET]
    requirements:
        attributeGroupId: \d+

ekyna_product_attribute_group_admin_move_down:
    path: /{attributeGroupId}/movedown
    defaults: { _controller: "ekyna_product.attribute_group.controller:moveDownAction" }
    methods: [GET]
    requirements:
        attributeGroupId: \d+

ekyna_product_attribute_group_admin_remove:
    path: /{attributeGroupId}/remove
    defaults: { _controller: "ekyna_product.attribute_group.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        attributeGroupId: \d+

ekyna_product_attribute_admin:
    resource: attribute.yml
    prefix: /{attributeGroupId}/attributes
