ekyna_product_attribute_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.attribute.controller:homeAction" }
    methods: [GET]

ekyna_product_attribute_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.attribute.controller:listAction" }
    methods: [GET|POST]

ekyna_product_attribute_admin_new:
    path: /new/{type}
    defaults: { _controller: "ekyna_product.attribute.controller:newAction" }
    methods: [GET|POST]
    requirements:
        type: '^[a-z]+$'

ekyna_product_attribute_admin_show:
    path: /{attributeId}/show
    defaults: { _controller: "ekyna_product.attribute.controller:showAction" }
    methods: [GET]
    requirements:
        attributeId: \d+

ekyna_product_attribute_admin_edit:
    path: /{attributeId}/edit
    defaults: { _controller: "ekyna_product.attribute.controller:editAction" }
    methods: [GET|POST]
    requirements:
        attributeId: \d+

ekyna_product_attribute_admin_move_up:
    path: /{attributeId}/moveup
    defaults: { _controller: "ekyna_product.attribute.controller:moveUpAction" }
    methods: [GET]
    requirements:
        attributeId: \d+

ekyna_product_attribute_admin_move_down:
    path: /{attributeId}/movedown
    defaults: { _controller: "ekyna_product.attribute.controller:moveDownAction" }
    methods: [GET]
    requirements:
        attributeId: \d+

ekyna_product_attribute_admin_remove:
    path: /{attributeId}/remove
    defaults: { _controller: "ekyna_product.attribute.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        attributeId: \d+

ekyna_product_attribute_choice_admin:
    resource: attribute_choice.yml
    prefix: /{attributeId}/choices
