ekyna_product_brand_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.brand.controller:homeAction" }
    methods: [GET]

ekyna_product_brand_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.brand.controller:listAction" }
    methods: [GET|POST]

ekyna_product_brand_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.brand.controller:newAction" }
    methods: [GET|POST]

ekyna_product_brand_admin_show:
    path: /{brandId}/show
    defaults: { _controller: "ekyna_product.brand.controller:showAction" }
    methods: [GET]
    requirements:
        brandId: \d+

ekyna_product_brand_admin_edit:
    path: /{brandId}/edit
    defaults: { _controller: "ekyna_product.brand.controller:editAction" }
    methods: [GET|POST]
    requirements:
        brandId: \d+

ekyna_product_brand_admin_tinymce:
    path: /{brandId}/tinymce/{_locale}/{field}
    controller: "ekyna_product.brand.controller:tinymceAction"
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        brandId: \d+
    defaults:
        _locale: "%locale%"
        field: description

ekyna_product_brand_admin_move_up:
    path: /{brandId}/moveup
    defaults: { _controller: "ekyna_product.brand.controller:moveUpAction" }
    methods: [GET]
    requirements:
        brandId: \d+

ekyna_product_brand_admin_move_down:
    path: /{brandId}/movedown
    defaults: { _controller: "ekyna_product.brand.controller:moveDownAction" }
    methods: [GET]
    requirements:
        brandId: \d+

ekyna_product_brand_admin_toggle:
    path: /{brandId}/toggle/{field}
    defaults: { _controller: "ekyna_product.brand.controller:toggleAction", field: visible }
    methods: [GET]
    requirements:
        brandId: \d+
        field: \w+

ekyna_product_brand_admin_remove:
    path: /{brandId}/remove
    defaults: { _controller: "ekyna_product.brand.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        brandId: \d+
