ekyna_product_category_admin_home:
    path: /
    defaults: { _controller: "ekyna_product.category.controller:homeAction" }
    requirements:
        _method: GET

ekyna_product_category_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.category.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_product_category_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.category.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_product_category_admin_new_child:
    path: /{categoryId}/new-child
    defaults: { _controller: "ekyna_product.category.controller:newChildAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+

ekyna_product_category_admin_show:
    path: /{categoryId}/show
    defaults: { _controller: "ekyna_product.category.controller:showAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_product_category_admin_edit:
    path: /{categoryId}/edit
    defaults: { _controller: "ekyna_product.category.controller:editAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+

ekyna_product_category_admin_tinymce:
    path: /{categoryId}/tinymce
    defaults: { _controller: "ekyna_product.category.controller:tinymceAction", field: html }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_product_category_admin_move_up:
    path: /{categoryId}/moveup
    defaults: { _controller: "ekyna_product.category.controller:moveUpAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_product_category_admin_move_down:
    path: /{categoryId}/movedown
    defaults: { _controller: "ekyna_product.category.controller:moveDownAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_product_category_admin_remove:
    path: /{categoryId}/remove
    defaults: { _controller: "ekyna_product.category.controller:removeAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+
