ekyna_product_category_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.category.controller:homeAction" }
    methods: [GET]

ekyna_product_category_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.category.controller:listAction" }
    methods: [GET|POST]

ekyna_product_category_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.category.controller:newAction" }
    methods: [GET|POST]

ekyna_product_category_admin_new_child:
    path: /{categoryId}/new-child
    defaults: { _controller: "ekyna_product.category.controller:newChildAction" }
    methods: [GET|POST]
    requirements:
        categoryId: \d+

ekyna_product_category_admin_show:
    path: /{categoryId}/show
    defaults: { _controller: "ekyna_product.category.controller:showAction" }
    methods: [GET]
    requirements:
        categoryId: \d+

ekyna_product_category_admin_edit:
    path: /{categoryId}/edit
    defaults: { _controller: "ekyna_product.category.controller:editAction" }
    methods: [GET|POST]
    requirements:
        categoryId: \d+

ekyna_product_category_admin_tinymce:
    path: /{categoryId}/tinymce/{_locale}/{field}
    controller: "ekyna_product.category.controller:tinymceAction"
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        categoryId: \d+
    defaults:
        _locale: "%locale%"
        field: description

ekyna_product_category_admin_move_up:
    path: /{categoryId}/moveup
    defaults: { _controller: "ekyna_product.category.controller:moveUpAction" }
    methods: [GET]
    requirements:
        categoryId: \d+

ekyna_product_category_admin_move_down:
    path: /{categoryId}/movedown
    defaults: { _controller: "ekyna_product.category.controller:moveDownAction" }
    methods: [GET]
    requirements:
        categoryId: \d+

ekyna_product_category_admin_toggle:
    path: /{categoryId}/toggle/{field}
    defaults: { _controller: "ekyna_product.category.controller:toggleAction", field: visible }
    methods: [GET]
    requirements:
        categoryId: \d+
        field: \w+

ekyna_product_category_admin_remove:
    path: /{categoryId}/remove
    defaults: { _controller: "ekyna_product.category.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        categoryId: \d+
