ekyna_product_highlight_admin_index:
    path: ""
    defaults: { _controller: EkynaProductBundle:Admin\Highlight:index }
    methods: [GET]

ekyna_product_highlight_admin_update:
    path: /{productId}/update
    defaults: { _controller: EkynaProductBundle:Admin\Highlight:update }
    methods: [POST]
    requirements: { productId: \d+ }
    options: { expose: true }
