ekyna_product_inventory_admin_index:
    path: ""
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:index }
    methods: [GET]

ekyna_product_inventory_admin_products:
    path: /products
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:products }
    methods: [GET]
    options:
        expose: true

ekyna_product_inventory_admin_quick_edit:
    path: /{productId}/quick-edit
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:quickEdit }
    methods: [GET, POST]
    options:
        expose: true

ekyna_product_inventory_admin_stock_units:
    path: /{productId}/stock-units
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:stockUnits }
    methods: [GET]
    options:
        expose: true

ekyna_product_inventory_admin_customer_orders:
    path: /{productId}/customer-orders
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:customerOrders }
    methods: [GET]
    options:
        expose: true

ekyna_product_inventory_admin_resupply:
    path: /{productId}/resupply
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:resupply }
    methods: [GET, POST]
    options:
        expose: true

ekyna_product_inventory_admin_export_products:
    path: /export-products
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:exportProducts }
    methods: [GET]

ekyna_product_inventory_admin_export_units:
    path: /export-units
    defaults: { _controller: EkynaProductBundle:Admin/Inventory:exportUnits }
    methods: [GET]
