ekyna_product_optionGroup_admin_home:
    path: /
    defaults: { _controller: "ekyna_product.optionGroup.controller:homeAction" }
    requirements:
        _method: GET

ekyna_product_optionGroup_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.optionGroup.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_product_optionGroup_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.optionGroup.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_product_optionGroup_admin_show:
    path: /{optionGroupId}/show
    defaults: { _controller: "ekyna_product.optionGroup.controller:showAction" }
    requirements:
        _method: GET
        optionGroupId:  \d+

ekyna_product_optionGroup_admin_edit:
    path: /{optionGroupId}/edit
    defaults: { _controller: "ekyna_product.optionGroup.controller:editAction" }
    requirements:
        _method: GET|POST
        optionGroupId:  \d+

ekyna_product_optionGroup_admin_remove:
    path: /{optionGroupId}/remove
    defaults: { _controller: "ekyna_product.optionGroup.controller:removeAction" }
    requirements:
        _method: GET|POST
        optionGroupId:  \d+
