ekyna_product_pricing_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.pricing.controller:homeAction" }
    methods: [GET]

ekyna_product_pricing_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.pricing.controller:listAction" }
    methods: [GET|POST]

ekyna_product_pricing_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.pricing.controller:newAction" }
    methods: [GET|POST]

ekyna_product_pricing_admin_show:
    path: /{pricingId}/show
    defaults: { _controller: "ekyna_product.pricing.controller:showAction" }
    methods: [GET]
    requirements:
        pricingId: \d+

ekyna_product_pricing_admin_edit:
    path: /{pricingId}/edit
    defaults: { _controller: "ekyna_product.pricing.controller:editAction" }
    methods: [GET|POST]
    requirements:
        pricingId: \d+

ekyna_product_pricing_admin_remove:
    path: /{pricingId}/remove
    defaults: { _controller: "ekyna_product.pricing.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        pricingId: \d+
