admin_ekyna_product_product_bookmark_add:
    path: /{productId}
    controller: Ekyna\Bundle\ProductBundle\Controller\Admin\ProductBookmarkController::add
    methods: POST
    requirements:
        productId: \d+
    options:
        expose: true

admin_ekyna_product_product_bookmark_remove:
    path: /{productId}
    controller: Ekyna\Bundle\ProductBundle\Controller\Admin\ProductBookmarkController::remove
    methods: DELETE
    requirements:
        productId: \d+
    options:
        expose: true
