ekyna_product_product_admin_home:
    path: ""
    controller: "ekyna_product.product.controller:homeAction"
    methods: [GET]

ekyna_product_product_admin_list:
    path: /list
    controller: "ekyna_product.product.controller:listAction"
    methods: [GET, POST]

ekyna_product_product_admin_export:
    path: /export
    controller: "ekyna_product.product.controller:exportAction"
    methods: [GET, POST]

ekyna_product_product_admin_attributes_form:
    path: /attributes-form/{attributeSetId}
    controller: "ekyna_product.product.controller:attributesFormAction"
    methods: [GET]
    requirements:
        attributeSetId: \d+
    options:
        expose: true

ekyna_product_product_admin_new:
    path: /new/{type}
    controller: "ekyna_product.product.controller:newAction"
    methods: [GET, POST]
    requirements:
        type: '^[a-z]+$'

ekyna_product_product_admin_show:
    path: /{productId}/show
    controller: "ekyna_product.product.controller:showAction"
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_summary:
    path: /{productId}/summary
    controller: "ekyna_product.product.controller:summaryAction"
    methods: [GET]
    requirements:
        productId: \d+
    options:
        expose: true

ekyna_product_product_admin_edit:
    path: /{productId}/edit
    controller: "ekyna_product.product.controller:editAction"
    methods: [GET, POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_move_up:
    path: /{productId}/move-up
    controller: "ekyna_product.product.controller:moveUpAction"
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_move_down:
    path: /{productId}/move-down
    controller: "ekyna_product.product.controller:moveDownAction"
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_duplicate:
    path: /{productId}/duplicate
    controller: "ekyna_product.product.controller:duplicateAction"
    methods: [GET, POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_convert:
    path: /{productId}/convert/{type}
    controller: "ekyna_product.product.controller:convertAction"
    methods: [GET, POST]
    requirements:
        productId: \d+
        type: '^[a-z]+$'

ekyna_product_product_admin_refresh_stock:
    path: /{productId}/refresh-stock
    controller: "ekyna_product.product.controller:refreshStockAction"
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_export_orders:
    path: /{productId}/export-orders
    controller: "ekyna_product.product.controller:exportOrders"
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_new_supplier_product:
    path: /{productId}/new-supplier-product
    controller: "ekyna_product.product.controller:newSupplierProductAction"
    methods: [POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_tinymce:
    path: /{productId}/tinymce/{_locale}/{field}
    controller: "ekyna_product.product.controller:tinymceAction"
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        productId: \d+
    defaults:
        _locale: "%locale%"
        field: description

ekyna_product_product_admin_toggle:
    path: /{productId}/toggle/{field}
    controller: "ekyna_product.product.controller:toggleAction"
    defaults:
        field: visible
    methods: [GET]
    requirements:
        productId: \d+
        field: \w+

ekyna_product_product_admin_remove:
    path: /{productId}/remove
    controller: "ekyna_product.product.controller:removeAction"
    methods: [GET, POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_generate_reference:
    path: /{productId}/generate-reference/{type}
    controller: "ekyna_product.product.controller:generateReference"
    methods: [GET]
    requirements:
        productId: \d+
        type: "[a-z0-9]+"

ekyna_product_product_admin_search:
    path: /search
    controller: "ekyna_product.product.controller:searchAction"
    methods: [GET]
    options:
        expose: true

ekyna_product_product_admin_label:
    path: /label/{format}.pdf
    controller: "ekyna_product.product.controller:labelAction"
    defaults:
        format: large
    methods: [GET]
    options:
        expose: true

ekyna_product_product_admin_find:
    path: /find
    controller: "ekyna_product.product.controller:findAction"
    methods: [GET]
    options:
        expose: true

ekyna_product_product_stock_unit_admin:
    resource: product_stock_unit.yml
    prefix: /{productId}/stock-units
