ekyna_product_product_admin_home:
    path: ""
    defaults: { _controller: "ekyna_product.product.controller:homeAction" }
    methods: [GET]

ekyna_product_product_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.product.controller:listAction" }
    methods: [GET|POST]

ekyna_product_product_admin_new:
    path: /new/{type}
    defaults: { _controller: "ekyna_product.product.controller:newAction" }
    methods: [GET|POST]
    requirements:
        type: '^[a-z]+$'

ekyna_product_product_admin_show:
    path: /{productId}/show
    defaults: { _controller: "ekyna_product.product.controller:showAction" }
    methods: [GET]
    requirements:
        productId: \d+

ekyna_product_product_admin_edit:
    path: /{productId}/edit
    defaults: { _controller: "ekyna_product.product.controller:editAction" }
    methods: [GET|POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_tinymce:
    path: /{productId}/tinymce
    defaults: { _controller: "ekyna_product.product.controller:tinymceAction", field: description }
    methods: [GET]
    requirements:
        field: "[a-zA-Z0-9]+"
        productId: \d+

#ekyna_product_product_admin_toggle:
#    path: /{productId}/toggle/{field}
#    defaults: { _controller: "ekyna_product.product.controller:toggleAction", field: enabled }
#    methods: [GET]
#    requirements:
#        productId: \d+
#        field: \w+

ekyna_product_product_admin_remove:
    path: /{productId}/remove
    defaults: { _controller: "ekyna_product.product.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        productId: \d+

ekyna_product_product_admin_search:
    path: /search
    defaults: { _controller: "ekyna_product.product.controller:searchAction" }
    methods: [GET]
    options:
        expose: true

ekyna_product_product_admin_find:
    path: /find
    defaults: { _controller: "ekyna_product.product.controller:findAction" }
    methods: [GET]
    options:
        expose: true
