ekyna_product_tax_admin_home:
    path: /
    defaults: { _controller: "ekyna_product.tax.controller:homeAction" }
    requirements:
        _method: GET

ekyna_product_tax_admin_list:
    path: /list
    defaults: { _controller: "ekyna_product.tax.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_product_tax_admin_new:
    path: /new
    defaults: { _controller: "ekyna_product.tax.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_product_tax_admin_show:
    path: /{taxId}/show
    defaults: { _controller: "ekyna_product.tax.controller:showAction" }
    requirements:
        _method: GET
        taxId:  \d+

ekyna_product_tax_admin_edit:
    path: /{taxId}/edit
    defaults: { _controller: "ekyna_product.tax.controller:editAction" }
    requirements:
        _method: GET|POST
        taxId:  \d+

ekyna_product_tax_admin_remove:
    path: /{taxId}/remove
    defaults: { _controller: "ekyna_product.tax.controller:removeAction" }
    requirements:
        _method: GET|POST
        taxId:  \d+
