doctrine:
    orm:
        entity_managers:
            default:
                hydrators:
                    OfferScalarHydrator: Ekyna\Bundle\ProductBundle\Doctrine\ORM\Hydrator\OfferScalarHydrator
                    PriceScalarHydrator: Ekyna\Bundle\ProductBundle\Doctrine\ORM\Hydrator\PriceScalarHydrator
