fos_elastica:
    indexes:
        search:
            types:
                ekyna_product_product:
                    serializer:
                        groups: [Search]
                    mappings:
                        reference: {type: string, search_analyzer: search, index_analyzer: index}
                        references: {type: string, search_analyzer: search, index_analyzer: index}
                    dynamic_templates:
                        en_title:
                            match_mapping_type: string
                            path_match: "*.en.title"
                            mapping: {type: string, boost: 3, search_analyzer: en_search, index_analyzer: en_index}
                        fr_title:
                            match_mapping_type: string
                            path_match: "*.fr.title"
                            mapping: {type: string, boost: 3, search_analyzer: fr_search, index_analyzer: fr_index}
                        en_default:
                            match_mapping_type: string
                            path_match: "*.en.*"
                            mapping: {type: string, search_analyzer: en_search, index_analyzer: en_index}
                        fr_default:
                            match_mapping_type: string
                            path_match: "*.fr.*"
                            mapping: {type: string, search_analyzer: fr_search, index_analyzer: fr_index}
                        default:
                            match_mapping_type: string
                            mapping: {type: string, search_analyzer: search, index_analyzer: index}
                    persistence:
                        driver: orm
                        model: "%ekyna_product.product.class%"
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: "%ekyna_product.product.search_repository.class%"
                ekyna_product_brand:
                    serializer:
                        groups: [Search]
                    dynamic_templates:
                        en_title:
                            match_mapping_type: string
                            path_match: "*.en.title"
                            mapping: {type: string, boost: 3, search_analyzer: en_search, index_analyzer: en_index}
                        fr_title:
                            match_mapping_type: string
                            path_match: "*.fr.title"
                            mapping: {type: string, boost: 3, search_analyzer: fr_search, index_analyzer: fr_index}
                        en_default:
                            match_mapping_type: string
                            path_match: "*.en.*"
                            mapping: {type: string, search_analyzer: en_search, index_analyzer: en_index}
                        fr_default:
                            match_mapping_type: string
                            path_match: "*.fr.*"
                            mapping: {type: string, search_analyzer: fr_search, index_analyzer: fr_index}
                        default:
                            match_mapping_type: string
                            mapping: {type: string, search_analyzer: search, index_analyzer: index}
                    persistence:
                        driver: orm
                        model: "%ekyna_product.brand.class%"
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: "%ekyna_product.brand.search_repository.class%"
                ekyna_product_category:
                    serializer:
                        groups: [Search]
                    dynamic_templates:
                        en_title:
                            match_mapping_type: string
                            path_match: "*.en.title"
                            mapping: {type: string, boost: 3, search_analyzer: en_search, index_analyzer: en_index}
                        fr_title:
                            match_mapping_type: string
                            path_match: "*.fr.title"
                            mapping: {type: string, boost: 3, search_analyzer: fr_search, index_analyzer: fr_index}
                        en_default:
                            match_mapping_type: string
                            path_match: "*.en.*"
                            mapping: {type: string, search_analyzer: en_search, index_analyzer: en_index}
                        fr_default:
                            match_mapping_type: string
                            path_match: "*.fr.*"
                            mapping: {type: string, search_analyzer: fr_search, index_analyzer: fr_index}
                        default:
                            match_mapping_type: string
                            mapping: {type: string, search_analyzer: search, index_analyzer: index}
                    persistence:
                        driver: orm
                        model: "%ekyna_product.category.class%"
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: "%ekyna_product.category.search_repository.class%"

