# Liip Imagine
liip_imagine:
    filter_sets:
        product_slide:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [320, 240], mode: outbound }
            post_processors:
                jpegoptim: {strip_all: true, max: "%image.jpeg_quality%", progressive: true}
                pngquant: {quality: "%image.png_quality%"}
        slot_thumb:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
            post_processors:
                jpegoptim: {strip_all: true, max: "%image.jpeg_quality%", progressive: true}
                pngquant: {quality: "%image.png_quality%"}
        slot_choice_btn:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [42, 42], mode: outbound }
            post_processors:
                jpegoptim: {strip_all: true, max: "%image.jpeg_quality%", progressive: true}
                pngquant: {quality: "%image.png_quality%"}
        slot_choice_thumb:
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [444, 333], mode: outbound }
            post_processors:
                jpegoptim: {strip_all: true, max: "%image.jpeg_quality%", progressive: true}
                pngquant: {quality: "%image.png_quality%"}
