# Liip Imagine
liip_imagine:
    filter_sets:
        slot_thumb:
            quality: 60
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [60, 60], mode: inbound }
            post_processors:
                jpegoptim: {}
        slot_choice_btn:
            quality: 60
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [42, 42], mode: inbound }
            post_processors:
                jpegoptim: {}
        slot_choice_thumb:
            quality: 60
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [444, 333], mode: outbound }
            post_processors:
                jpegoptim: {}
