admin_ekyna_product_product_bookmark:
    resource: admin/product_bookmark.yaml
    prefix: /product-bookmark

admin_ekyna_product_stock_view:
    resource: admin/stock_view.yaml
    prefix:   /stock

admin_ekyna_product_highlight:
    resource: admin/highlight.yaml
    prefix:   /highlight
