# Ticket
ekyna_product_account_catalog_index:
    path: ''
    methods: [GET]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::index
    options:
        ekyna_18n: ~
        _cms:
            name: Mes catalogues
            parent: ekyna_user_account_index
            position: 70
            locked: true
            advanced: false
            seo:
                follow: false
                index: false

ekyna_product_account_catalog_create:
    path: /create
    methods: [GET, POST]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::create

ekyna_product_account_catalog_show:
    path: /{catalogId}
    methods: [GET]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::show
    requirements:
        catalogId: \d+

ekyna_product_account_catalog_edit:
    path: /{catalogId}/edit
    methods: [GET, POST]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::edit
    requirements:
        catalogId: \d+

ekyna_product_account_catalog_remove:
    path: /{catalogId}/remove
    methods: [GET, POST]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::remove
    requirements:
        catalogId: \d+

ekyna_product_account_catalog_print:
    path: /{catalogId}/print
    methods: [GET, POST]
    controller: Ekyna\Bundle\ProductBundle\Controller\Account\CatalogController::render
    requirements:
        catalogId: \d+
